# Generated by Django 4.2.1 on 2023-09-10 14:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='is_pose_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='pose_path',
            field=models.FileField(blank=True, null=True, upload_to=api.models.pose_upload_to),
        ),
    ]
