# Generated by Django 4.2.1 on 2023-09-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_videoupload_is_pose_processing_videoupload_pose_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='poseLandmarkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_values', models.TextField()),
                ('y_values', models.TextField()),
                ('z_values', models.TextField()),
                ('visibility_values', models.TextField()),
                ('presence_values', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.videoupload')),
            ],
        ),
    ]
